# Generated by Django 5.2.6 on 2025-10-19 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coworkings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slots',
            new_name='Slot',
        ),
    ]
