# Generated by Django 5.2.6 on 2025-11-19 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworkings', '0002_rename_slots_slot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'verbose_name': 'Слот', 'verbose_name_plural': 'Слоты'},
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='room',
            name='limit',
            field=models.IntegerField(verbose_name='Лимит'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('desk', 'Рабочее место'), ('meeting_room', 'Переговорная')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.DateTimeField(verbose_name='Время конца'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Слот', to='coworkings.room'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время начала'),
        ),
    ]
